# From: https://www.elastic.co/guide/en/elastic-stack-get-started/7.4/get-started-docker.html
version: '3.0'

services:

# For development we add Kibana to test searches, etc
  kib01:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  flask:
    ports:
      - 5000:5000

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
