# From: https://www.elastic.co/guide/en/elastic-stack-get-started/7.4/get-started-docker.html
version: '3.0'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
        - 0.0.0.0:9200:9200
        - 127.0.0.1:9200:9200
    expose:
        - 9200
    networks:
      - elastic

  flask:
    build: flask-app/
    container_name: flask01
    volumes:
      - ./flask-app:/app
    expose:
      - 5000 
    restart: always
    environment:
      FLASK_ENV: development
    networks:
      - elastic

  ngnix:
    build: nginx/
    container_name: ngnix01
    restart: always
    ports:
      - "80:80"
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
