# From: https://www.elastic.co/guide/en/elastic-stack-get-started/7.4/get-started-docker.html
version: '3.0'

services:
  flask:
    ports:
      - 80:5000
    environment:
      FLASK_ENV: production
